version: "3"

services:
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messengerdb
    restart: always
    stop_grace_period: 30s
    ports:
      - "5432"

    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest


  django:
    build: .
    command:  bash -c " python manage.py makemigrations && python manage.py migrate
                        &&  python manage.py runserver 0.0.0.0:8000 "

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - pg
